Removes AGP 8+ incompatible Gradle property 'android.disableAutomaticComponentCreation' to resolve:
Build file '/accuterra_sdk_android/DemoApp/build.gradle' line: 1

A problem occurred evaluating project ':DemoApp'.
> Failed to apply plugin 'com.android.internal.application'.
> com.android.builder.errors.EvalIssueException: The option 'android.disableAutomaticComponentCreation' is deprecated.
It was removed in version 8.0 of the Android Gradle plugin.
Please remove it from `gradle.properties`.

See SDK project commit 6692fc2931243f141f873195a6874b375bf8fad3